### ISSUE TITLE
MTB00-Inception

### ISSUE THREAD

**Issue by glixius** [glixius/masterboard#1]
# MTB00-Inception

We need to setup an app with state management and json serialization capabilities.

## Tasks
- [x] Add built_value to project.
- [x] Add built_collection to project.
- [x] Add redux to project.

**Comment by glixius** [comment]
Feature solved by Pull request #2 

Closing.
