### ISSUE TITLE
MTB01 | Layout

### ISSUE THREAD

**Issue by glixius** [glixius/masterboard#3]
## Tasks

- [ ] Add general navigation.
- [ ] Add clubs related navigation.
- [ ] Add leagues related navigation.
- [ ] Add drawer navigation.
- [ ] Add loader component.
- [ ] Add snackbar component.
- [ ] Add dialog component.
- [ ] Setup icon library.

**Comment by glixius** [comment]
Layout is gonna be generated based on wireframes defined on #1
