### ISSUE TITLE
MTB01 | Handle Ping Pong Scoreboard

### ISSUE THREAD

**Issue by glixius** [glixius/masterboard#3]
### Description

Masterboard's main feature is to record games. It's gonna start with ping pong games.

### Acceptance criteria

- [ ] We are gonna record single ping pong games with standard 11 points set. Bo3.
- [ ] Game scoreboard must display: competitors, match score, current set score and play b y play history.
- [ ] App must handle winning conditions for sets (First to make it to 11 points or first to make a 2 point difference)
- [ ] App must handle game winning conditions.
- [ ] App must display winning state when game is over.
- [ ] App must allow user to record points for both competitors. 

### Tasks

- [ ] Remove boilerplate code.
- [ ] Create Game model.
- [ ] Create store for game.
- [ ] Create Scoreboard view.
- [ ] Add scoreboard actions.
- [ ] Implement winning conditions.
- [ ] Add win view.
